name: Build & Publish Release APK

on:
  push:
    branches:
      - main
      
jobs:
  build-android-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - uses: AndreaMolinari/rn-conventional-release@v1.0.0